### ISSUE TITLE
Multi module example?

### ISSUE THREAD

**Issue by JohnBuhanan** [olshevski/compose-navigation-reimagined#1]
I am trying out this library this morning and struggling to make it work for a multi-module example.

I'm thinking contribute each features NavHost with dagger multi-bindings.

Any tips?

**Comment by olshevski** [comment]
Can you please provide details on what you are trying to achieve and what exactly is failing?

I'm not sure I understand your problem.

**Comment by nathlrowe** [comment]
I'm just here to report that I've had no trouble getting this to work with multiple modules. Both where it's the destination composable content, and where it's an entire NavHost that's in the dependency module.

I really don't understand why you would need multi-bindings for compose navigation in general. The NavHost is a composable function, not an object. You shouldn't be trying to inject a nav controller anywhere either.

**Comment by olshevski** [comment]
Glad to hear that you figured it out in the end.
