### ISSUE TITLE
CreationExtras integration

### ISSUE THREAD

**Issue by equeim** [olshevski/compose-navigation-reimagined#10]
androidx.lifecycle 2.5 added new API for easier creation of custom ViewModel factories. It needs some integration from this library.

Namely, NavHostEntry needs to override getDefaultViewModelCreationExtras() method to set default CreationExtras keys that users expect to be present (application, saved state registry owner, etc). Here is how ComponentActivity does that: https://github.com/androidx/androidx/blob/7f29447f3add52b6db69524dfa944dd1b0a8828b/activity/activity/src/main/java/androidx/activity/ComponentActivity.java#L641

**Comment by olshevski** [comment]
Support added in [1.2.0](https://github.com/olshevski/compose-navigation-reimagined/releases/tag/1.2.0).
