### ISSUE TITLE
BottomSheet support

### ISSUE THREAD

**Issue by hrach** [olshevski/compose-navigation-reimagined#11]
Hello, I cannot find any mention of bottomsheet. How does it work with this library? Is it expected to use DialogNavigator to show those bottomsheet? I expect that bottomsheet is a bit more complicated as some swiping down should skip further animation (the swipe already animated the destination removal or it should continue animating). Thank you

**Comment by olshevski** [comment]
@hrach Hi, there is no current integration with `ModalBottomSheetLayout` and `BottomSheetScaffold`. And yes, it is actually not that trivial to implement. I'm planning to give it a go in the future, but not yet.

For now, I can suggest using `DialogNavHost` with `BottomSheetDialog` from this library: https://github.com/holixfactory/bottomsheetdialog-compose

I've tested it and it works great. Just be aware of this small issue: https://github.com/holixfactory/bottomsheetdialog-compose/issues/1

Until developers fix the issue, it can be handled in this way (see how `dismissCalled` prevents the second accidental `pop`):

```kotlin
val navController = rememberNavController<DialogNavHostDestination>(
    initialBackstack = emptyList()
)

DialogNavHost(navController) { destination ->
    var dismissCalled by remember { mutableStateOf(false) }
    BottomSheetDialog(onDismissRequest = {
        if (!dismissCalled) {
            dismissCalled = true
            navController.pop()
        }
    }) {
        when (destination) {
            DialogNavHostDestination.First -> FirstDialogLayout(
                toSecondDialogButtonClick = { navController.navigate(DialogNavHostDestination.Second) }
            )
            DialogNavHostDestination.Second -> SecondDialogLayout()
        }
    }
}
```

**Comment by hrach** [comment]
Thank you for the response. What's the motivation not to use the material bottom sheet?

**Comment by olshevski** [comment]
I'm not sure what do you mean.

**Comment by hrach** [comment]
Yes, I mean the Compose Material implementation. Bringing the View system or even the View's  bottomsheet behavior seems quite non-optimal to me and we will always lack the latest features for Compose.

**Comment by olshevski** [comment]
But it is the same as using composable Dialogs. It is just a separate window with a compose layout inside. I've used this library in a separate project and find it so much more convenient for simple cases rather than `ModalBottomSheetLayout` and `BottomSheetScaffold`.

But again, I'm not strictly against Compose's implementations, just give me the time, I have ideas on how it could be done better. But not at these exact moment. Sorry for inconvenience.

**Comment by olshevski** [comment]
`BottomSheetNavHost` is finally implemented as part of `reimagined-material` artifact in version 1.3.0.
