### ISSUE TITLE
AnimatedNavHost breaks with Compose 1.4.0-beta02 after orientation change

### ISSUE THREAD

**Issue by equeim** [olshevski/compose-navigation-reimagined#16]
1. Update Compose to 1.4.0-beta02
2. Add configChanges to <activity/> in AndroidManifest.xml so that Activity won't be recreated on orientation change (instead content will be simply recomposed):
```
android:configChanges="density|layoutDirection|locale|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|keyboard"
```
3. Launch app, perform at least one navigation (bug doesn't reproduce without this)
4. Change device orientation

After that whole app's content will be shifted halfway to the top or left of screen.
Replacing AnimatedNavHost with plain NavHost "fixes" this.

I realise that this version of Compose is not released to stable yet but it is still worth taking a look at least to report it upstream if the bug is in Compose.

![Screenshot_20230224-002042](https://user-images.githubusercontent.com/5106414/221032946-cd7fd9f0-1afc-4485-8074-3303bd9734f3.png)

**Comment by olshevski** [comment]
@equeim It seems to be an issue with `AnimatedContent` that is used in the library. I've reported the issue to Google: https://issuetracker.google.com/issues/270656253

**Comment by olshevski** [comment]
@equeim I've found a way to overcome this bug. Specifying `Modifier.fillMaxSize()` seems to make `AnimatedContent` behave correctly. (Although I still think something is broken in AnimatedContent itself and it should work without this modifier. But it is for Google employees to make the judgement.)

`AnimatedNavHost` doesn't currently expose `modifier` parameter, so I've added it. It is available in the snapshot:

```
repositories {
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```
```
implementation("dev.olshevski.navigation:reimagined:1.3.2-20230225.184517-2")
```

Then declare AnimatedNavHost like this:
```kotlin
AnimatedNavHost(
    controller = navController,
    modifier = Modifier.fillMaxSize()
) {
    // ...
}
```

Can you please test it for your app and tell me if it works now?

**Comment by olshevski** [comment]
The issue doesn't seem to be present anymore in the final 1.4.0 version of Compose.
