### ISSUE TITLE
[Bug] Crash with compose 1.5.0-alpha04

### ISSUE THREAD

**Issue by T8RIN** [olshevski/compose-navigation-reimagined#23]
![image](https://github.com/olshevski/compose-navigation-reimagined/assets/52178347/8da7aef8-4490-4a2a-a4a5-5faf7ffaf05b)

It crashes with this error, also i've got crash on the 1.5.0-alpha03 :((

[1.5.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.5.0-alpha04)

**Comment by olshevski** [comment]
Yeah, they renamed AnimatedContentScope to something else. I'll create a new alpha build for Compose 1.5.0.

**Comment by T8RIN** [comment]
Thanks a lot! I cannot use the latest libs now(

**Comment by olshevski** [comment]
@T8RIN I've published version 1.5.0-alpha01 of the library. It should be compatible with changes in pre-release Compose 1.5.0

(It may take up to an hour for a new version to appear in Maven Central)

**Comment by T8RIN** [comment]
Thanks for the quick response!
