### ISSUE TITLE
A bottom sheet with scroll breaks the BottomSheetNavHost

### ISSUE THREAD

**Issue by za4em** [olshevski/compose-navigation-reimagined#24]
I use the sample app(without any changes)  to produce this bug. 

Steps to produce:
- Open a bottom sheet
- Scroll down fast 
- Scroll up fast
- Close the bottom sheet using swipe.

After that the navigation stops working.

There is a video with this:
https://github.com/olshevski/compose-navigation-reimagined/assets/14274854/83a6eb67-9384-4ff3-a3d9-3eb5576f2c48

**Comment by olshevski** [comment]
Thank you for reporting the issue. I've found the root cause of it and fixed it. The fix will appear sometime in the next release. Please let me know if you need a patch for 1.4.0. I can make a snapshot version.

**Comment by za4em** [comment]
@olshevski Thanks! 
It would be nice to get the snapshot version.

**Comment by olshevski** [comment]
@za4em Are you using Compose 1.4.0 or one of 1.5.0-alpha builds? There are breaking changes in 1.5.0 Compose Animations API, so I'm running 2 separate version of the library at the moment.

**Comment by za4em** [comment]
@olshevski I'm using 1.4.0

**Comment by olshevski** [comment]
@za4em Here you go:
```
implementation("dev.olshevski.navigation:reimagined:1.4.1-20230512.084454-1")
```

In order to use Maven Central snapshot, please add this repo:
```
repositories {
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by olshevski** [comment]
@za4em Can you please check and confirm that the issue is resolved on your side with this fix?

**Comment by za4em** [comment]
@za4em Yes, the issue is resolved in the snapshot version.
