### ISSUE TITLE
Disable dismiss?

### ISSUE THREAD

**Issue by GytisBarakauskas** [olshevski/compose-navigation-reimagined#33]
Hey, is there a way to disable dismissing the bottom sheet? E.g. it should not be swipeable and clicking on scrim would not close it too. I couldn't find it in documentation and looking at the code.

EDIT: actually empty onDismiss would work, but is there a way to disable swiping?

Thanks.

EDIT2: I just added a `sheetLayoutModifier = Modifier.pointerInteropFilter { true }` and it seems to do the trick.

**Comment by olshevski** [comment]
@GytisBarakauskas I adopted the API from the official ModalBottomSheetLayout, so swiping gestures and scrim clicks are disabled with this parameters:

```kotlin
sheetPropertiesSpec = {
    BottomSheetProperties(confirmValueChange = { it != BottomSheetValue.Hidden })
},
```

Basically it doesn't allow to transition to `Hidden` state. Note, however, that the bottom sheet still will react to swipes, it will just always return to Expanded/HalfExpanded state as it has been before. A bit weird to my taste, but that is how `ModalBottomSheetLayout` works, so I decided not to mess with people's expectations.

I definitely might have missed this in documentation, as I assumed for some reason people might be familiar with the official API. My bad.

**Comment by GytisBarakauskas** [comment]
I never really bothered to play around with official navigation, since it has quite a bad reputation.

Thank you for so fast answer! I guess for my use case this will do nicely.

**Comment by olshevski** [comment]
@GytisBarakauskas

>I never really bothered to play around with official navigation, since it has quite a bad reputation.

Me too, haha. But I really meant ModalBottomSheetLayout from just the Compose Material package.

Also, note that you can provide different properties for each bottom sheet, in case only some of them should be non-dismissable.
