### ISSUE TITLE
How do you do dependency injection here?

### ISSUE THREAD

**Issue by hi-brylle** [olshevski/compose-navigation-reimagined#35]
I ask for a recommended architecture of how Repositories can be instantiated using this library. Manual dependency injection for now (because I want to learn it before using Hilt).

Thank you :)

**Comment by olshevski** [comment]
@hi-brylle Sorry for the late response. Have you already found the answer to your question?

The library does not impose any particular way to instantiate classes or use DI. I'm not even sure what exactly you want to know. Is there any particular problem you want to solve?

**Comment by hi-brylle** [comment]
Hello, yes, I have already found a solution to my problem: just some simple constructor injection for my top-level Composable function containing `compose-navigation-reimagined` code). Thank you for the reply though.

People looking for a more proper DI solution should **not** follow what I did here in my app's prototype.
