### ISSUE TITLE
Cannot create View Model class using hiltViewModel()

### ISSUE THREAD

**Issue by andraantariksa** [olshevski/compose-navigation-reimagined#7]
The title says it all. It only happen for ViewModel inside of the NavHost

This is the error

```
java.lang.UnsupportedOperationException: SavedStateViewModelFactory constructed with empty constructor supports only calls to create(modelClass: Class<T>, extras: CreationExtras).
```

Step to reproduce
- Clone https://github.com/andraantariksa/crates
- Run the project

**Comment by olshevski** [comment]
androidx.hilt:hilt-navigation-compose works only with the official Navigation Component for Compose.

My library is not related to Navigation Component in any way. As a temporary solution you may take hiltViewModel method sources from androidx.hilt:hilt-navigation-compose and replace `NavBackStackEntry` with `NavComponentEntry`.

You may find useful the discussion here: https://github.com/olshevski/compose-navigation-reimagined/discussions/4

**Comment by olshevski** [comment]
Also, I don't even see you using my library in the github repo you've linked to. How can I help you with then?

**Comment by andraantariksa** [comment]
Sorry, I can't follow your instruction correctly, so I just revert everything to compose navigation.
